"""ajustes modelo user/profile registro completo

Revision ID: 777a890143d2
Revises: 334c4cbd5938
Create Date: 2025-10-17 16:25:14.452733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777a890143d2'
down_revision: Union[str, Sequence[str], None] = '334c4cbd5938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
