"""multi-tenant add tenant_id + uniques

Revision ID: c753630dc1c7
Revises: 777a890143d2
Create Date: 2025-10-21 19:04:14.933805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c753630dc1c7'
down_revision: Union[str, Sequence[str], None] = '777a890143d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('attempts', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_attempts_tenant_id'), 'attempts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'attempts', 'tenants', ['tenant_id'], ['id'])
    op.add_column('badges', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_badges_tenant_id'), 'badges', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'badges', 'tenants', ['tenant_id'], ['id'])
    op.add_column('courses', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'tenants', ['tenant_id'], ['id'])
    op.add_column('exercises', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_exercises_tenant_id'), 'exercises', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'exercises', 'tenants', ['tenant_id'], ['id'])
    op.add_column('leaderboard_daily', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leaderboard_daily_tenant_id'), 'leaderboard_daily', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leaderboard_daily', 'tenants', ['tenant_id'], ['id'])
    op.add_column('lesson_blocks', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lesson_blocks_tenant_id'), 'lesson_blocks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lesson_blocks', 'tenants', ['tenant_id'], ['id'])
    op.add_column('lessons', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lessons_tenant_id'), 'lessons', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'tenants', ['tenant_id'], ['id'])
    op.add_column('media_assets', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_media_assets_tenant_id'), 'media_assets', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'media_assets', 'tenants', ['tenant_id'], ['id'])
    op.add_column('modules', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_modules_tenant_id'), 'modules', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'modules', 'tenants', ['tenant_id'], ['id'])
    op.add_column('posts', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_posts_tenant_id'), 'posts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'tenants', ['tenant_id'], ['id'])
    op.add_column('profiles', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_profiles_tenant_id'), 'profiles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'profiles', 'tenants', ['tenant_id'], ['id'])
    op.add_column('streaks', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_streaks_tenant_id'), 'streaks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'streaks', 'tenants', ['tenant_id'], ['id'])
    op.add_column('teacher_feedback', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_teacher_feedback_tenant_id'), 'teacher_feedback', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'teacher_feedback', 'tenants', ['tenant_id'], ['id'])
    op.add_column('threads', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_threads_tenant_id'), 'threads', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'threads', 'tenants', ['tenant_id'], ['id'])
    op.add_column('user_badges', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_badges_tenant_id'), 'user_badges', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_badges', 'tenants', ['tenant_id'], ['id'])
    op.add_column('user_progress', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_progress_tenant_id'), 'user_progress', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_progress', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_user_tenant_email', 'users', ['tenant_id', 'email'])
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.add_column('xp_events', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_xp_events_tenant_id'), 'xp_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'xp_events', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xp_events', type_='foreignkey')
    op.drop_index(op.f('ix_xp_events_tenant_id'), table_name='xp_events')
    op.drop_column('xp_events', 'tenant_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_user_tenant_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_index(op.f('ix_user_progress_tenant_id'), table_name='user_progress')
    op.drop_column('user_progress', 'tenant_id')
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.drop_index(op.f('ix_user_badges_tenant_id'), table_name='user_badges')
    op.drop_column('user_badges', 'tenant_id')
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_index(op.f('ix_threads_tenant_id'), table_name='threads')
    op.drop_column('threads', 'tenant_id')
    op.drop_constraint(None, 'teacher_feedback', type_='foreignkey')
    op.drop_index(op.f('ix_teacher_feedback_tenant_id'), table_name='teacher_feedback')
    op.drop_column('teacher_feedback', 'tenant_id')
    op.drop_constraint(None, 'streaks', type_='foreignkey')
    op.drop_index(op.f('ix_streaks_tenant_id'), table_name='streaks')
    op.drop_column('streaks', 'tenant_id')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_tenant_id'), table_name='profiles')
    op.drop_column('profiles', 'tenant_id')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_tenant_id'), table_name='posts')
    op.drop_column('posts', 'tenant_id')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_index(op.f('ix_modules_tenant_id'), table_name='modules')
    op.drop_column('modules', 'tenant_id')
    op.drop_constraint(None, 'media_assets', type_='foreignkey')
    op.drop_index(op.f('ix_media_assets_tenant_id'), table_name='media_assets')
    op.drop_column('media_assets', 'tenant_id')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_tenant_id'), table_name='lessons')
    op.drop_column('lessons', 'tenant_id')
    op.drop_constraint(None, 'lesson_blocks', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_blocks_tenant_id'), table_name='lesson_blocks')
    op.drop_column('lesson_blocks', 'tenant_id')
    op.drop_constraint(None, 'leaderboard_daily', type_='foreignkey')
    op.drop_index(op.f('ix_leaderboard_daily_tenant_id'), table_name='leaderboard_daily')
    op.drop_column('leaderboard_daily', 'tenant_id')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_tenant_id'), table_name='exercises')
    op.drop_column('exercises', 'tenant_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_column('courses', 'tenant_id')
    op.drop_constraint(None, 'badges', type_='foreignkey')
    op.drop_index(op.f('ix_badges_tenant_id'), table_name='badges')
    op.drop_column('badges', 'tenant_id')
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_index(op.f('ix_attempts_tenant_id'), table_name='attempts')
    op.drop_column('attempts', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
